### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'find'

### ISSUE THREAD

**Issue by patrickESM** [brjathu/PHALP#14]
Dear brjathu,

When running the demo script as suggested in the Readme i encounter the following error:

`(phalp) D:\.linux\projects_github\PHALP>python scripts/demo.py video.source="https://www.youtube.com/watch?v=xEH_5T9jMVU"

pkg://hydra.conf
D:\.linux\projects_github\PHALP\configs

Traceback (most recent call last):
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\utils.py", line 356, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\hydra.py", line 61, in create_main_hydra2
    config_loader: ConfigLoader = ConfigLoaderImpl(
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\config_loader_impl.py", line 48, in __init__
    self.repository = ConfigRepository(config_search_path=config_search_path)
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\config_repository.py", line 65, in __init__
    self.initialize_sources(config_search_path)
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\config_repository.py", line 72, in initialize_sources
    scheme = self._get_scheme(search_path.path)
  File "C:\Users\pschuelein\anaconda3\envs\phalp\lib\site-packages\hydra\_internal\config_repository.py", line 144, in _get_scheme
    idx = path.find("://")
AttributeError: 'WindowsPath' object has no attribute 'find'`

the first two lines are added prints of myself.

Did I configure something wrong during install or am I calling the script incorrect?

All help much appreciated :)

Thanks

**Comment by brjathu** [comment]
Can ypu please try to replace this line:

https://github.com/brjathu/PHALP/blob/8076c653d0a64c64ea18012ae42975bc903fba18/scripts/demo.py#L20

```python
@hydra.main(version_base="1.2", config_path="..\configs", config_name="base.yaml")
```

**Comment by brjathu** [comment]
@patrickESM We have updated the code and now support better models and easy install. Could you please try again and let us know?

**Comment by patrickESM** [comment]
thank you for the line change answer regarding config paths.

This works fine. thank you!

Regarding the new models i will try as well

**Comment by brjathu** [comment]
Thank you.
