### ISSUE TITLE
OpenGL.error.GLError when running with some videos

### ISSUE THREAD

**Issue by garrisonz** [brjathu/PHALP#30]
I cut two shot video (dancing2.mp4, dancing3.mp4) from a same long video.
dancing2.mp4： https://github.com/brjathu/PHALP/assets/1321005/6867121d-3f85-46f5-b351-68aa871a7a1f
dancing3.mp4： https://github.com/brjathu/PHALP/assets/1321005/8a2cef07-f936-48d6-9df2-3cb84fdb55aa

PHALP with dancing2.mp4 work 
PHALP with dancing3.mp4 throws an error as following 

```
(phalp2) :~/3dhuman/PHALP$ python scripts/demo.py video.source=assets/videos/dancing3.mp4 video.output_dir='outputs7'
[03/17 01:12:51] INFO     No OpenGL_accelerate module loaded: No module named                   acceleratesupport.py:17
                          'OpenGL_accelerate'
[2024-03-17 01:12:53,960][pytorch_lightning.utilities.migration.utils][INFO] - Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.2.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../.cache/4DHumans/logs/train/multiruns/hmr2/0/checkpoints/epoch=35-step=1000000.ckpt`
[2024-03-17 01:12:53,964][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpqwevip08
[2024-03-17 01:12:53,964][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpqwevip08/_remote_module_non_scriptable.py
WARNING: You are using a SMPL model, with only 10 shape coefficients.
[2024-03-17 01:12:56,972][phalp.trackers.PHALP][INFO] - Loading Predictor model...
[2024-03-17 01:12:57,111][phalp.trackers.PHALP][INFO] - Loading Detection model...
[2024-03-17 01:13:01,881][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692/model_final_f05665.pkl ...
[2024-03-17 01:13:03,885][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/139653917/model_final_2d9806.pkl ...
[2024-03-17 01:13:03,984][phalp.trackers.PHALP][INFO] - Setting up Visualizer...
[2024-03-17 01:13:04,293][phalp.utils.io][INFO] - Number of frames: 115
[2024-03-17 01:13:05,283][phalp.trackers.PHALP][INFO] - Setting up DeepSort...
[2024-03-17 01:13:05,283][phalp.trackers.PHALP][INFO] - Saving tracks at : outputs7/results/dancing3
Tracking : dancing3 🚶  ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   4% eta : 0:01:11  time elapsed : 0:00:04
GLError(
        err = 12289,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fe0559b1940>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fe05c8f4f40>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fe05c8f4f40>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fe0559b25c0>,
        ),
        result = 0
)
Traceback (most recent call last):
  File "/home/zhangyupeng/w/3drecon/3dhuman/PHALP/phalp/trackers/PHALP.py", line 252, in track
    rendered_, f_size = self.visualizer.render_video(final_visuals_dic[frame_key])
  File "/home/zhangyupeng/w/3drecon/3dhuman/PHALP/phalp/visualize/visualizer.py", line 359, in render_video
    rendered_image_final, valid_mask  = self.render_single_frame(
  File "/home/zhangyupeng/w/3drecon/3dhuman/PHALP/phalp/visualize/visualizer.py", line 77, in render_single_frame
    rgb_from_pred, validmask = self.render.visualize_all(pred_vertices.numpy(), pred_cam_t_bs.cpu().numpy(), color, image, use_image=use_image)
  File "/home/zhangyupeng/w/3drecon/3dhuman/PHALP/phalp/visualize/py_renderer.py", line 115, in visualize_all
    color = self.__call__(verts, focal_length=fl, baseColorFactors=baseColorFactors)
  File "/home/zhangyupeng/w/3drecon/3dhuman/PHALP/phalp/visualize/py_renderer.py", line 152, in __call__
    color, rend_depth = self.renderer.render(scene, flags=pyrender.RenderFlags.RGBA)
  File "/home/zhangyupeng/miniconda3/envs/phalp2/lib/python3.10/site-packages/pyrender/offscreen.py", line 86, in render
    self._platform.make_current()
  File "/home/zhangyupeng/miniconda3/envs/phalp2/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 196, in make_current
    assert eglMakeCurrent(
  File "/home/zhangyupeng/miniconda3/envs/phalp2/lib/python3.10/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglMakeCurrent,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fe0559b1940>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fe05c8f4f40>,
                <OpenGL._opaque.EGLSurface_pointer object at 0x7fe05c8f4f40>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fe0559b25c0>,
        ),
        result = 0
)


```

**Comment by srikanth-ml-dev** [comment]
@garrisonz i am facing the same issue, did you solve it?. If you have solved it please can you post the solution
Thank yOU

**Comment by srikanth-ml-dev** [comment]
@garrisonz 
in py_render.py after calling the Renderer try using the below method to delete the renderer 
def __del__(self):
       del self.renderer
This worked for me

**Comment by daviduarte** [comment]
Same error here. I resolved it by reencoding all my videos using the latest version of FFMPEG. Installing FFMPEG from apt results in an older ffmpeg installation. I compiled it from source. Afterwards, I reencoded using:

`ffmpeg -i video.mp4 -c:v h264 -an new_video.mp4`

**Comment by fgz-ai** [comment]
I faced the same error and it's happening quit regular across different videos. 
The suggestion for video conversion using ffmpeg didn't help.

Any idea how to work around this error?
