### ISSUE TITLE
AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by daviduarte** [brjathu/PHALP#34]
Erro reproduction: 
- Download [this video from UCF-Crime dataset:](https://drive.google.com/file/d/1s7z1sBoaV_axWJ01sYh-0_15LLavWKwv/view?usp=drive_link)
- Exec:
`python3 scripts/demo.py video.source=Normal_Videos465_x264.mp4 video.output_dir=./output`

It will raise an error:

```
Traceback (most recent call last):
  File "/home/lecun/davi/PHALP/phalp/trackers/PHALP.py", line 205, in track
    self.tracker.update(detections, t_, frame_name, self.cfg.phalp.shot)
  File "/home/lecun/davi/PHALP/phalp/external/deep_sort_/tracker.py", line 83, in update
    self.accumulate_vectors([i[0] for i in matches], features=self.cfg.phalp.predict)
  File "/home/lecun/davi/PHALP/phalp/external/deep_sort_/tracker.py", line 179, in accumulate_vectors
    if("P" in features): p_pred = self.phalp_tracker.forward_for_tracking([p_features, p_data, t_features], "P", l_time)
  File "/home/lecun/davi/PHALP/phalp/trackers/PHALP.py", line 491, in forward_for_tracking
    pose_pred = self.pose_predictor.predict_next(en_pose, en_data, en_time, time)
  File "/home/lecun/davi/PHALP/phalp/models/predictor/pose_transformer_v2.py", line 398, in predict_next
    t_end.append(t.item())
AttributeError: 'int' object has no attribute 'item'
```

**Comment by daviduarte** [comment]
Possible solution:
- In PHALP/phalp/models/predictor/pose_transform_v2
- replace
`t_end.append(t.item())`
to
`t_end.append(t.item() if torch.is_tensor(t) else t)`

**Comment by effegma-ai** [comment]
The same error is occuring using other Videos.

**Comment by lishisen01** [comment]
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/head_faces.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/mean_std.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/smpl_mean_params.npz
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/SMPL_to_J19.pkl
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/3D/texture.npz
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/bmap_256.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/fmap_256.npy
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/hmar_v2_weights.pth
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/pose_predictor_40006.ckpt
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/weights/config_40006.yaml
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/ava_labels.pkl
https://people.eecs.berkeley.edu/~jathushan/projects/phalp/ava/ava_class_mappping.pkl
When I was accessing these downloaded files, the links were all broken. Can anyone help me find where I can still find a backup of the files? Or if anyone has saved a backup of this file, could you please share it with me? Thank you so much
